#cloud-config
package_update: true
package_upgrade: true
packages:
  - gnome-core
  - jq
  - curl

runcmd:
# insira aqui o que deve ser feito
# Cria o usuário VDI e entra na pasta do usuário
  - useradd -m -s /bin/bash ${user_instance} && cd "/home/${user_instance}"
  - '[ ! -d "/home/${user_instance}/projetos" ] && mkdir "/home/${user_instance}/projetos"'
  - cd /home/${user_instance}/projetos

# Pegando a ultima versão do repositório services
  - TAG_NAME=$(curl -s https://api.github.com/repos/nettaskjr/services/releases/latest | jq -r '.tag_name')
  - ASSET_URL=$(curl -s https://api.github.com/repos/nettaskjr/services/releases/latest | jq -r ".tarball_url")
  - curl -L -o "services-${TAG_NAME}.tar.gz" "$ASSET_URL"
  - tar -zxvf "services-${TAG_NAME}.tar.gz"
  - chmod +x *.sh

# Instala o pacote services
# sudo ./00-run.sh '${var.client}' '${var.host}' '${var.user-ec2}' '${var.email}' ${var.apps}
  - sudo ./00-run.sh 'pessoal' 'localhost' '${var.user_instance}' 'pessoal@pessoal.com' ''

final_message: "A instância está configurada. O servidor VNC deve estar rodando para o usuário ${user} na display :1 (porta 5901)."
